### PR TITLE
Drop `DotNetStep`

### PR DESCRIPTION
**Pull request by Zastai**
When used in a pipeline, the builders did not get access to the correct environment. As a result, they would ignore SDK selection via the `tools` section, or through the use of the `withDotNet` wrapper.
To work around this issue `DotNetStep` was used; but this was relatively hackish (it used a system intended only for use by the pipeline library).
Starting with Jenkins 2.241, API is available to enable builders to receive the correct environment, so this workaround was no longer needed. This PR switches to that API, and bumps the required Jenkins version to 2.249.1 (the first LTS release to include the API).

### CODE REVIEW

**Comment by h1dden-da3m0n** [comment]
sorry to random comment, but would this change not also deserve a `breaking` and `removed` label?

(both are supported by the [release drafter config](https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.yml) in the organisations .github repo)

**Comment by Zastai** [comment]
Hmm, I would have assumed the GitHub label dropdown would also be set up to include all release drafter labels; guess it isn't. If I'd seen those in the list I would have considered applying them (even though it's still in the 0.x "anything can change" stage).

Not too sure about `breaking`; `DotNetStep` would not be directly in use - it was a metastep, so only used at runtime by the pipeline library to wrap the regular builders. `removed` certainly applies though.

**Comment by h1dden-da3m0n** [comment]
I was aware that this Plugin is still in pre 1.0 territory, but I simply felt like mentioning/asking this.
Yeah sadly the GH labels aren't set-up per default for all the labels that the orgs Release Drafter supports, but then again how would they?
I guess you are right about the `breaking` part, like I mentioned this was more a drive by comment than and educated one based on review. (Thank you for response btw :grinning: )

**Comment by Zastai** [comment]
I rather assumed the label list could/would also be inherited from the org.
Anyway, I have now manually ensured that I have a label set for all Release Drafter categories. Thanks for the drive-by :)

**Pull request merged**
